### PR TITLE
Colab

### PR DESCRIPTION
**Pull request by jburel**
This PR adds the ability to run the notebooks in colab
This is similar to what we put in place in https://github.com/ome/omero-guide-python

### CODE REVIEW

**Comment by joshmoore** [comment]
Went looking to see if anyone had built a layer that made this a non-issue for the user. Instead, I found https://www.dataschool.io/cloud-services-for-jupyter-notebook/ which makes me worry we may get requests for even _more_ platforms...

**Comment by jburel** [comment]
There is certainly some other options out there. The community is mainly using binder and colab
see for example https://bioimage.io/

**Comment by jburel** [comment]
I think it will be good to have that in place ahead of next week course
cc @pwalczysko @francesw

**Comment by pwalczysko** [comment]
Do you want to add a "launch in Colab" badge to the README just like on the omero-guide-python ?

**Comment by jburel** [comment]
That's what the commit 37c71434b74d53813c30bce19ff44e91543b2106 does

**Comment by pwalczysko** [comment]
> That's what the commit [37c7143](https://github.com/IDR/idr-notebooks/commit/37c71434b74d53813c30bce19ff44e91543b2106) does

ah, sorry, yes, I can see it now

**Comment by pwalczysko** [comment]
I cannot see in the diff that you would change the  "Calculate Sharpness"  notebook, and , indeed, it crashes in Colab.

```

ImportErrorTraceback (most recent call last)

<ipython-input-1-379312543b75> in <module>()
      8 from scipy import misc
      9 from IPython.display import HTML
---> 10 from idr import connection

ImportError: No module named idr
```

**Comment by jburel** [comment]
I have not changed than one since it should be removed cf. https://github.com/IDR/idr-notebooks/pull/104

**Comment by pwalczysko** [comment]
The "Figure 1" notebook crashes on the "Load grouping of phenotypes..." step.
I believe this was not changed in this PR though ?

```
FileNotFoundError                         Traceback (most recent call last)

<ipython-input-8-a718ce1785b7> in <module>()
      1 # The table was built offline using biomart
----> 2 dfTrans = read_csv('./includes/TableOfGenesWithElongatedCellPhenotype.csv')
      3 
      4 # extract IDs
      5 key = 'Human Ortholog Ensembl 84'

4 frames

/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   2008         kwds["usecols"] = self.usecols
   2009 
-> 2010         self._reader = parsers.TextReader(src, **kwds)
   2011         self.unnamed_cols = self._reader.unnamed_cols
   2012 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] No such file or directory: './includes/TableOfGenesWithElongatedCellPhenotype.csv'
```

**Comment by jburel** [comment]
The notebook probably needs to be improved, paths are probably handled differently

**Comment by pwalczysko** [comment]
The "Rohn" notebook fails with

```
InternalException                         Traceback (most recent call last)

<ipython-input-8-a0715feda7ff> in <module>()
----> 1 dfRhonAnn, phenotype_count = getBulkAnnotationAsDf(screenId, conn)

1 frames

/usr/local/lib/python3.7/dist-packages/omero_SharedResources_ice.py in openTable(self, file, _ctx)
    432         """
    433         def openTable(self, file, _ctx=None):
--> 434             return _M_omero.grid.SharedResources._op_openTable.invoke(self, ((file, ), _ctx))
    435 
    436         """

InternalException: exception ::omero::InternalException
{
    serverStackTrace = 
    serverExceptionClass = 
    message = null table as argument
}

```

**Comment by jburel** [comment]
Looks like the table cannot be retrieved. Does it work in binder?

**Comment by pwalczysko** [comment]
QueryIDRwithGenesLists fails with 

```---------------------------------------------------------------------------

HTTPError                                 Traceback (most recent call last)

<ipython-input-5-a24a3e189e65> in <module>()
      5  screen_to_phenotype_dictionary] = get_phenotypes_for_genelist(session,
      6                                                                go_gene_list,
----> 7                                                                organism)
      8 display(HTML(query_genes_dataframe.to_html(escape=False)))

2 frames

/usr/local/lib/python3.7/dist-packages/requests/models.py in raise_for_status(self)
    939 
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 
    943     def close(self):

HTTPError: 504 Server Error: Gateway Time-out for url: https://idr.openmicroscopy.org/mapr/api/organism/?value=Homo%20sapiens
```

**Comment by pwalczysko** [comment]
PCAnalysis of Charm Features hangs forever on  "Finding the rows of the table we are interested in" cell (no error)

**Comment by pwalczysko** [comment]
> Looks like the table cannot be retrieved. Does it work in binder?

Yes, Rohn notebook, the particular cell ("Download the annotation file...") worked fine in Binder (it is still doing the "Gallery", but the problem described in https://github.com/IDR/idr-notebooks/pull/109#issuecomment-877166367 for Colab does not repeat in Binder.

**Comment by pwalczysko** [comment]
in summary, the notebooks which had problems on Colab:

  - [Figure 1 and GeneNetwork](https://github.com/IDR/idr-notebooks/pull/109#issuecomment-877142512) (same problem for both notebooks)
  - [Rohn](https://github.com/IDR/idr-notebooks/pull/109#issuecomment-877166367)
  - [Query ifr](https://github.com/IDR/idr-notebooks/pull/109#issuecomment-877171958)

**Comment by jburel** [comment]
* Ran the ``RohnPhenotypeClustering`` notebook in colab and it works.

**Comment by jburel** [comment]
QueryIDRWithGeneLists: the query takes a long time. This notebook was written when a limited of data was available in IDR
I think we need to review the notebook itself and have  a reduce query.
This is not a "colab" problem as such


a12a1b1 should fix the problem when reading the CSV

**Comment by pwalczysko** [comment]
Retested Rohn notebook and works as expected. Also the notebooks fixed in https://github.com/IDR/idr-notebooks/commit/a12a1b14e3ce76cadd21ef26f4f5445c52507bd6 work fine. Understand that the QueryIDRWithGeneLists is having a problem independent of this PR.

Ready to merge fmpov

**Pull request merged**
