### PR TITLE
Binder

### PR DESCRIPTION
**Pull request by jburel**
Modify the structure so that the notebook can be run via binderhub

@manics we probably need to have a discussion about notebooks testing before I remove the ``docker`` folder.
I have removed travis (initially modified) by the action's template repo2docker.yml.
https://github.com/jburel/idr-notebooks/actions/runs/429812650

### CODE REVIEW

**Comment by manics** [comment]
Can we deploy https://github.com/IDR/deployment/pull/285 to production instead of making all these custom changes to the notebooks, especially as the main idea behind the `idr.connection` library is to wrap the connection logic?

**Comment by jburel** [comment]
If the PR is deployed, yes we can roll back.
The changes in this PR were made before the deployment PR

**Comment by manics** [comment]
Aside from the connection changes, I tested the two modified notebooks on mybinder.
`SysgroOverview` was fine, `GeneNetwork` returned this error:
image

**Comment by jburel** [comment]
there is no logic change in ``GeneNetwork``, only a reformatting of the variable so the error is probably not related to the change

**Comment by jburel** [comment]
Ok the error in ``GeneNetwork`` is due to a change in stringdb api. I hit a similar problem when working on idr-py

**Comment by jburel** [comment]
Even with https://github.com/IDR/deployment/pull/285 deployed, we still get the error
```
/srv/conda/envs/notebook/lib/python3.7/site-packages/omero/clients.py in _initData(self, id)
    299                 msg = "No host specified. "
    300                 msg += "Use omero.client(HOSTNAME), ICE_CONFIG, or similar."
--> 301                 raise omero.ClientError(msg)
    302 
    303             if not self.__ic:

ClientError: No host specified. Use omero.client(HOSTNAME), ICE_CONFIG, or similar.
```
when using ``conn = connection()``

**Comment by manics** [comment]
This works:
`conn = connection('idr.openmicroscopy.org')`
I've just tried it

**Comment by jburel** [comment]
Ok, I went back to the old way i.e. ``connection()``

**Comment by jburel** [comment]
@manics: I have reverted the connection and fixed the stringdb query in ``GeneNetwork``.

**Comment by dominikl** [comment]
Looks good. The `GeneNetwork` notebook is now much faster too. Tested a few others too, with local docker build and on mybinder. LGTM 👍 On `Figure_1_Sampling_of_Phenotypes` notebook I got an `InternalException: null table as argument`, but that's definitely not an issue with this PR, I'll create an issue for that.

**Comment by jburel** [comment]
@dominikl issue created https://github.com/IDR/idr-py/issues/25

**Pull request merged**
