### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by jburel**
bump cellprofiler and rgateway version

To test:
* go to https://ome-lochy.openmicroscopy.org
* select snoopycrimecop/idr-notebooks:itr_merge_daily
* check that you can connect to idr
* Try to run the r notebook and the cellProfiler one

See https://github.com/idr-contrib/community/issues/16 
CellProfiler upgrade was mentioned during a monthly EOSC-Life call

### CODE REVIEW

**Comment by joshmoore** [comment]
```
Errored, use --debug for full output:
ValueError: 
"jupyterlab_bokeh@0.6.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/apputils
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/notebook
The command '/bin/sh -c conda env update -n python2 -q -f .setup/environment-python2-idr.yml &&     jupyter labextension install jupyterlab_bokeh@^0.6.0' returned a non-zero code: 1
The command "docker build -t idr-notebooks ." exited with 1.
```

**Comment by joshmoore** [comment]
(Otherwise, makes sense)

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#832](https://ci.openmicroscopy.org/job/DOCKER-merge/832/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/832/consoleText) for more details.
Possible conflicts:
  - PR #86 jburel 'R-base upgrade'
    - Dockerfile

--conflicts

**Comment by jburel** [comment]
The last failure is strange since the same version of mysql works on training-notebooks repo see
https://travis-ci.org/ome/training-notebooks/builds/553602980

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#833](https://ci.openmicroscopy.org/job/DOCKER-merge/833/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/833/consoleText) for more details.
Possible conflicts:
  - PR #86 jburel 'R-base upgrade'
    - Dockerfile

--conflicts

**Comment by jburel** [comment]
> The last failure is strange since the same version of mysql works on training-notebooks repo see
> https://travis-ci.org/ome/training-notebooks/builds/553602980

The difference is the version the base image 0.9.0 for training and 0.9.2 for this repo. The problem now shows up for training too now.

**Comment by jburel** [comment]
cc @beatrizserrano

**Comment by dominikl** [comment]
Was a bit difficult to test. As ome-lochy gives 404, I built the docker image locally using https://github.com/snoopycrimecop/idr-notebooks/tree/itr_merge_daily .
I assume that's why for example in the R notebook things like:
```
IDR_HOST <- Sys.getenv("IDR_HOST")
IDR_USER <- Sys.getenv("IDR_USER")
IDR_PASSWORD <- Sys.getenv("IDR_PASSWORD")
IDR_PORT <- Sys.getenv("IDR_PORT", 4064)
```
don't work in a local build. However putting the host, username, etc. in manually, I was able to run the R notebook.

But I was not able to run the CP notebook, because:
```
from idr import connection; 
conn = connection()
print conn
```
does not work in the local build either. Don't know how to manually bypass that in the case of the CP notebook.
Guess ideally this should be tested on ome-lochy. Is it possible to get it running again?

**Comment by dominikl** [comment]
Can't test it. For some reason this PR is not applied (also snoopy says it's merged). If I run `sessionInfo()` in an R notebook I get: `R version 3.4.1 (2017-06-30)`, although should be `3.5` according to the PR.

**Comment by jburel** [comment]
unless the image has not been built and deployed

**Comment by jburel** [comment]
image has now been rebuilt.
The changes match the training ones.
Merging and tagging so external can use it

**Pull request merged**
