### PR TITLE
Figure1 phenotype categories feb2017

### PR DESCRIPTION
**Pull request by eleanorwilliams**
@joshmoore and @ac744 

I have 
- added CMPOAccessionToPhenotypeCategoriesFeb2017.csv which includes phenotypes mapped to CMPO for idr0011 and idr0028 so figure generated here will match the updated one in the paper.
- updated Figure_1_Sampling_of_Phenotypes.ipynb so that it refers to this new file (rather than the old CMPOAccessionToPhenotypeCategoriesNov2016.csv).  

One question - would it be better to have a file without the date in the name so we don't need to keep updating the notebook file (Figure_1_Sampling_of_Phenotypes.ipynb)?

### CODE REVIEW

**Comment by joshmoore** [comment]
I'd vote yes. GitHub will have the history. So the changes to the notebook here could be reverted.

**Comment by eleanorwilliams** [comment]
@joshmoore. I updated the files so the date is not longer mentioned in the file name.

**Comment by joshmoore** [comment]
I reverted the Python-related changes to the file. Merging for prod36

**Comment by eleanorwilliams** [comment]
@joshmoore Where have the python related changes come from - is it because I have Python 3 in my local set up of Jupyter?

**Pull request merged**
