### PR TITLE
Compound

### PR DESCRIPTION
**Pull request by jburel**
Explore compounds
This is the first round
We can more section like generate a figure afterwards

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
The third graph does not have axis labels, the first two graphs do.

Screenshot 2021-05-07 at 15 18 02

**Comment by jburel** [comment]
@pwalczysko The problem should now be fixed.
Thanks for spotting it

**Comment by jburel** [comment]
That's probably due to the entry in the dataframe without concentration.
I will need to filter the dataframe to only keep the one with values before plotting

**Comment by pwalczysko** [comment]
> That's probably due to the entry in the dataframe without concentration.
> I will need to filter the dataframe to only keep the one with values before plotting

Even better would be to plot it anyway, but as a description display "not given" or "unknown". This would give the user the overview of how many images are there with only half-description of the compound (but not concentration)

**Comment by jburel** [comment]
@pwalczysko: I have replaced ``-`` by ``unknown`` so we can highlight as suggested that the info is missing

**Comment by pwalczysko** [comment]
thank you, tested, works fine. Ready to merge fmpov

**Pull request merged**
