### PR TITLE
Move notebooks to top-level, Add Dockerfile

### PR DESCRIPTION
**Pull request by manics**
Uses the new proposed base image for OME notebooks:
- [x] --depends-on https://github.com/IDR/jupyter-docker/pull/26
Moves notebooks into the top-level as discussed elsewhere

An nice benefit of this is that this repo should work with http://mybinder.org/ e.g. https://mybinder.org/v2/gh/manics/idr-notebooks/jupyter-0.8 (only http/https is allowed so notebooks using the OMERO API won't work)

- [ ] --depends-on https://github.com/IDR/jupyter-docker/pull/29 since the bokeh jupyterlab extension requires an updated version of jupyterlab

## Testing
```
docker build -t idr-notebooks .
docker run -it --rm -p 8888:8888 -e IDR_HOST=idr.openmicroscopy.org -e IDR_USER=<USER> -e IDR_PASSWORD=<PASSWORD> idr-notebooks
```

### CODE REVIEW

**Comment by manics** [comment]
The last commit ensures the `notebooks/` dir will match the content of the source repo/branch used for the build. Examination of the automated build image on Docker Hub shows this is a depth=1 single commit clone or something along those lines. https://stackoverflow.com/a/21217267/8062212 suggests this should still be usable.

**Comment by joshmoore** [comment]
The biggest issue would likely be if any notebook was relying on a tag (I don’t know of that). For the moment, users could always fetch/pull if they needed to.

**Comment by manics** [comment]
One additional change we could consider is renaming `docker/` to `.docker/` to hide it from the standard notebooks list

**Comment by jburel** [comment]
scikit-learn is not installed either in https://github.com/manics/idr-notebooks/blob/1ed24c2b98a17d0c6c5a91ac1b96a563be1530aa/docker/environment-python2-idr.yml nor in https://github.com/IDR/jupyter-docker/blob/master/environment-python2.yml
this means that PCAanalysis is not usable anymore

**Comment by jburel** [comment]
Adding scikit-learn and the extension of bokeh work fine

**Comment by manics** [comment]
Will be tagged as `0.8.1` as discussed in slack.

**Comment by jburel** [comment]
jupyter-docker will be tagged at 0.8.1

4284c4c will need to be reverted when tagged

**Pull request merged**
