### PR TITLE
QueryIDRWithGeneLists: Fix default ID for GO and update notebook

### PR DESCRIPTION
**Pull request by bramalingam**
ref: #47 (comment)

Dealing with mostly the high and blocker items alone.

@sbesson

### CODE REVIEW

**Comment by sbesson** [comment]
While the changes including the default value for the GO id make sense, successive executions of this notebook against the staging server fail when querying other genes from phenotypes. On the other hand, the notebooks works as expected against the production IDR.

**Comment by manics** [comment]
Does the original notebook without changes fail against staging?

**Comment by sbesson** [comment]
This is the original behavior I get:

Test | Production notebook | Staging notebook
 -|-----|-----
Staging server  | fail | fail
Production server | pass |  pass

Note that the production notebook does not have any default GO ID, so I used the one provided in this notebook for comparison.

After a a series of iterations against the staging server, the query seems to be failing at later stages until it finally succeeds. It looks there is likely some level of caching of the query happening on the server.

**Comment by sbesson** [comment]
After a few executions, the query run by the notebook seems to have been cached on the staging server. This is probably something we need to look into incl. tuning the PSQL server. For IDR 0.4.5, however, this is probably sufficient. Merging.

**Pull request merged**
