### PR TITLE
Roi formatting

### PR DESCRIPTION
**Pull request by joshmoore**
Various changes to @ac744's notebook as a template for other workshop notebooks. For discussion:

 * **titles**: start with caps, camel case (leaving getting started-style notebooks to have underscores). What term per study? Author like Rohn? Sysgro as here? (Whatever works?)
 * **headers**: H1 (`#`) at the top, H3 (`###`) below. There are likely exceptions.
 * **licenses**: at the bottom ok?
 * **connections**: open wherever, but close as soon as possible (explicitly)
 * **imports**: all at the top. Should we prefer `import x`, `import x as y` or `from x import y` or whatever works?
 * **inline comments**: to be minimized in favor of method doc strings and markdown?
 * **formatting**: PEP8 please. I'll try to add a checker.

More specific to this notebook:

 * new name ok?
 * extract the methods out to a library?

cc:  @eleanorwilliams @bramalingam @dominikl @ac744 @sbesson @jburel

### CODE REVIEW

**Comment by joshmoore** [comment]
(travis failure is due to missing .travis.yml file)

**Comment by eleanorwilliams** [comment]
Looks like a nice layout to me.  Perhaps put a separate title in for 'Setup Imports' or 'Setup' so that there is a nice clear separation of the intro and the start of the code?

**Comment by joshmoore** [comment]
@eleanorwilliams, like that?

**Comment by joshmoore** [comment]
Please feel free to continue the discussion here. I'm merging to get these deployed on minke.

**Comment by eleanorwilliams** [comment]
@joshmoore - that is even more thorough that I am was meaning. Looks great.

**Comment by sbesson** [comment]
Few latest comments:

- titles: works for me. We could consider also using the accession number for study-specific notebook to be explicit/prevent ambiguity but this might be at the cost of readability.
- headers: :+1: H1/H3 should be cover most cases
- licenses: :+1: Is the license the same across notebooks or are variations allowed? (in which case a top-level `LICENSE` could be added)
- connections: :+1:for explicit deconnection with header
- imports: :+1: for PEP8 top-level convention. No strong opinion on import styles might vary depending on what is imported. 
- inline comments: agreed. the need for many inline comments is probably a good rule of thumb to refactor the code using a function with a docstring
- formatting: :+1:

**Pull request merged**
