### PR TITLE
GeneAndPhenotypeQueries notebook

### PR DESCRIPTION
**Pull request by eleanorwilliams**
This is a notebook that might be used in the November EMBL-predocs training session at EBI. 
It uses idr.py and I'm not sure how you set up the test environment to include the latest version of this.

Questions:

1. Should the functions get_genes_for_phenotype and getenrichedterms be in idr.py?
2. Should the connection details be somewhere else?
3. Can we change the output of the enrichment so that it doesn't show the old p values?

### CODE REVIEW

**Comment by bramalingam** [comment]
The notebook works as expected, could you please consider the following changes,

- please remove the `pip install gseapy` line from the notebook (this should be part of the jupyter-docker)
- Redundant import of gseapy package, could you please remove one of the import lines
- please update the title for the enrichment analysis cell to the following : “### Create a function to do the enrichment analysis and then print out the top 5 enriched categories”

**Comment by eleanorwilliams** [comment]
@bramalingam I think I have made all the necessary changes.

**Comment by eleanorwilliams** [comment]
One comment though - a directory called ../notebooks/Enrichr/ is created.  Is this going to work in the read only environment of the production notebooks?  Maybe I need to create this directory in advance?

**Comment by manics** [comment]
It's not read-only, everything is inside the docker notebook container

**Comment by manics** [comment]
(Though it would be better if you didn't create files outside the idr-notebooks directory.)

**Comment by eleanorwilliams** [comment]
Closing this PR in favour of https://github.com/IDR/idr-notebooks/pull/46 which has both notebooks in the same PR

**Pull request closed without merging**
