### PR TITLE
R-base upgrade

### PR DESCRIPTION
**Pull request by jburel**
Bump version to fix build

see https://github.com/ome/training-notebooks/pull/25/commits/e899564bace779d6961bb2d436b564625e267a36

### CODE REVIEW

**Comment by jburel** [comment]
See https://hub.docker.com/r/snoopycrimecop/training-notebooks/builds/bd3mxzgjj32rflmmz5cbmz/

**Comment by jburel** [comment]
bokehjs-itr

**Comment by dominikl** [comment]
Looks good and certainly works on jupyterhub-internal with 'training-notebooks:master_merge_daily', `sessionInfo()` output:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS
...
```
But is that enough for testing this PR?

**Comment by jburel** [comment]
This PR was fixing the build.
So now that it is green and running
This should be enough

**Comment by dominikl** [comment]
👍

**Comment by jburel** [comment]
Closing, replaced by https://github.com/IDR/idr-notebooks/pull/92

**Pull request closed without merging**
