### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by jburel**
Upgrade version to match JupyterLab version

### CODE REVIEW

**Comment by jburel** [comment]
tested today and looks fine 
cc @manics

**Comment by manics** [comment]
Using `conda install nbval` and the `test_notebooks.sh` from https://github.com/IDR/idr-notebooks/pull/88

```
__________________________________ notebooks/GeneNetwork.ipynb::Cell 9 ___________________________________
Notebook cell execution failed
Cell 9: Cell execution caused an exception

Input:
import warnings
warnings.filterwarnings('ignore')
g = nx.from_pandas_dataframe(df, 2, 3)
plt.figure(figsize = (12, 12))
nx.draw_spring(g, with_labels=True)

Traceback:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-87f18234787b> in <module>()
      1 import warnings
      2 warnings.filterwarnings('ignore')
----> 3 g = nx.from_pandas_dataframe(df, 2, 3)
      4 plt.figure(figsize = (12, 12))
      5 nx.draw_spring(g, with_labels=True)

AttributeError: 'module' object has no attribute 'from_pandas_dataframe'
```
[Stackoverflow](https://stackoverflow.com/questions/49223057/attributeerror-module-networkx-has-no-attribute-from-pandas-dataframe/49580740#49580740) suggests changing `from_pandas_dataframe` to `from_pandas_edgelist`.

**Comment by manics** [comment]
## Extract length of cells as stored in ROIs in the IDR

This cell prints out a deprecation message:
```
/opt/conda/envs/python2/lib/python2.7/site-packages/skimage/measure/_regionprops.py:250: UserWarning: regionprops and image moments (including moments, normalized moments, central moments, and inertia tensor) of 2D images will change from xy coordinates to rc coordinates in version 0.16.
See http://scikit-image.org/docs/0.14.x/release_notes_and_installation.html#deprecations for details on how to avoid this message.
  warn(XY_TO_RC_DEPRECATION_MESSAGE)
```
I think this is due to the calls to `skmes.regionprops` in `getLengthsFromStrain`. Since it's a deprecation it wouldn't normally be a problem as it still runs, except that in this case it prints out the deprecation 920 times.

**Comment by manics** [comment]
@jburel I've pushed three commits to your branch/PR:
- Fix the two deprecations I mentioned
- Change the base image from `latest` to `0.9.0`

I'd like to get this merged so I can start working on updating the notebooks for nbval.

**Pull request merged**
