### PR TITLE
Minke changes (2)

### PR DESCRIPTION
**Pull request by joshmoore**
* Replace gh-28 and gh-26

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
My changes look correctly incorporated.

**Comment by joshmoore** [comment]
@bramalingam : please note the file renaming. If you think this will conflict, please let me know.

**Comment by joshmoore** [comment]
Note: testing with

```
[jamoore@minke joshmoore]$ sudo -u omeroot perl -i -pe 's#idr.openmicroscopy.org/jupyter#jupyter.openmicroscopy.org/jupyter#g' README.* notebooks/Using_Jupyter.ipynb
```

**Comment by joshmoore** [comment]
GenesToPhenotypes updated, @eleanorwilliams.

**Comment by eleanorwilliams** [comment]
In README.ipynb and README.md

- maybe change 'paper' in the Level column to 'IDR paper'?
- GeneNetwork description in table - remove comma at the end of 'resulting network.,' 
- GeneNetwork description in table - space after 'biomart', remove '.' after 'details.'
- GeneNetwork  description in table - I don't think it uses py2cytoscape to display networks. I think it uses bokeh and networkx (https://networkx.github.io/). 
- Condensation Bulk Annotations description in table - remove 'Accesses'
- Rohn Phenotype Clustering description in table - change IDR008 to idr0008-rohn-actinome

GeneNetworks.ipynb
- I don't know if this is an issue but the visualization of networkx network is shown in github but not the one from bokeh

Overview.ipynb - i can see an error at 'conn.close()' when viewed in github but I haven't actually tried to run it. 

Note: I haven't tested the notebooks out. I can run them if needed.

**Comment by joshmoore** [comment]
* README updated (pushing in a second)
 * I've removed Overview. I have it privately if I want to show anyone.
 * bokeh: no it won't work on GitHub. You have to use nbviewer for that.

**Comment by joshmoore** [comment]
Merging this (travis' being red is a false negative due new notebooks being listed in the README) and deploying.

**Pull request merged**
